/**
 * vendor.js — Copies runtime assets out of node_modules into public/vendor/.
 *
 * The app self-hosts its icons and Arabic font rather than pulling them from a
 * CDN. That keeps it working offline, on a locked-down network, and when
 * unpkg or Google Fonts is slow — and removes a render-blocking third party.
 *
 * Runs automatically on `npm start` via the prestart hook.
 */

import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const VENDOR = path.join(ROOT, 'public', 'vendor');
const FONT_DIR = path.join(VENDOR, 'fonts');

// Weights actually referenced by the stylesheet. Shipping only these keeps the
// payload down; the Latin subset comes along for mixed Arabic/Latin strings.
const WEIGHTS = [300, 400, 500, 600, 700];
const SUBSETS = ['arabic', 'latin'];

async function copy(from, to) {
  await fs.mkdir(path.dirname(to), { recursive: true });
  await fs.copyFile(from, to);
}

async function main() {
  await fs.mkdir(FONT_DIR, { recursive: true });

  // --- Icons ---
  await copy(
    path.join(NM, 'lucide/dist/umd/lucide.min.js'),
    path.join(VENDOR, 'lucide.min.js')
  );
  console.log('  ✓ lucide.min.js');

  // --- Font files + a generated @font-face sheet ---
  const src = path.join(NM, '@fontsource/ibm-plex-sans-arabic/files');
  const faces = [];
  let copied = 0;

  for (const subset of SUBSETS) {
    for (const weight of WEIGHTS) {
      const file = `ibm-plex-sans-arabic-${subset}-${weight}-normal.woff2`;
      try {
        await copy(path.join(src, file), path.join(FONT_DIR, file));
        copied += 1;
        faces.push(`@font-face {
  font-family: 'IBM Plex Sans Arabic';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('./fonts/${file}') format('woff2');
}`);
      } catch {
        // A missing subset/weight combination is not fatal — the browser falls
        // back to the nearest available weight.
      }
    }
  }

  await fs.writeFile(
    path.join(VENDOR, 'fonts.css'),
    `/* Generated by scripts/vendor.js — do not edit by hand. */\n\n${faces.join('\n\n')}\n`,
    'utf8'
  );
  console.log(`  ✓ fonts.css + ${copied} ملف خط`);
}

main().catch((err) => {
  console.error('فشل تجهيز ملفات vendor:', err.message);
  process.exit(1);
});
